export const descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Tiger',
    'Leopard',
    'Elephant',
    'Peacock',
    'Banyan',
    'Sandalwood',
    'Bamboo',
    'Teak',
    'Monsoon',
    'Himalayan',
    'Sacred',
    'Royal',
    'Imperial',
    'Spice',
    'Tea',
    'Coffee',
    'Golden',
    'Emerald',
    'Tropical',
    'Highland',
    'Wild',
    'Hidden',
    'Spiritual',
    'Sunset',
    'Sunrise',
    'Jungle'
]

export const places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Valley',
    'Meadows',
    'Hill Station',
    'Viewpoint',
    'Reserve',
    'Sanctuary',
    'Fort',
    'Ruins',
    'Falls',
    'Lake',
    'Woods',
    'Grove',
    'Basecamp',
    'Pass',
    'Trails',
    'Peak',
    'Estate',
    'Retreat',
    'Summit',
    'Plateau',
    'Ridge',
    'Gorge',
    'Haven',
    'Oasis'
]